/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicas.Semana4.Universidad.presentation.ui;
/**
 *
 * @author cerna
 */
public class Universidad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Universidad.class.getName());

    /**
     * Creates new form Universidad
     */
    public Universidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNotaAlumnoId = new javax.swing.JTextField();
        txtNotaCursoNombre = new javax.swing.JTextField();
        txtNotaProfesorId = new javax.swing.JTextField();
        txtNotaValor = new javax.swing.JTextField();
        btnRegistrarNotaAparte = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCarreraId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCarreraNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCursoId = new javax.swing.JTextField();
        txtCursoDescripcion = new javax.swing.JTextField();
        txtCursoNombre = new javax.swing.JTextField();
        txtCursoHoras = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtProfesorId = new javax.swing.JTextField();
        txtProfesorNombre = new javax.swing.JTextField();
        txtProfesorSueldo = new javax.swing.JTextField();
        txtProfesorTelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAlumnoId = new javax.swing.JTextField();
        txtAlumnoDireccion = new javax.swing.JTextField();
        txtAlumnoTelefono = new javax.swing.JTextField();
        txtAlumnoEmail = new javax.swing.JTextField();
        txtSeccionAula = new javax.swing.JTextField();
        txtSeccionId = new javax.swing.JTextField();
        btnRegistrarMatricula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("ID DE ALUMNO : ");

        jLabel18.setText("NOMBRE DEL CURSO :");

        jLabel19.setText("ID PROFESOR :");

        jLabel20.setText("NOTA :");

        txtNotaAlumnoId.addActionListener(this::txtNotaAlumnoIdActionPerformed);

        txtNotaCursoNombre.addActionListener(this::txtNotaCursoNombreActionPerformed);

        btnRegistrarNotaAparte.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarNotaAparte.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarNotaAparte.setText("NOTA");
        btnRegistrarNotaAparte.addActionListener(this::btnRegistrarNotaAparteActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrarNotaAparte)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel18))
                                            .addGap(13, 13, 13))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addComponent(txtNotaAlumnoId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNotaProfesorId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNotaValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtNotaCursoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(715, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtNotaAlumnoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtNotaCursoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(txtNotaProfesorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtNotaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnRegistrarNotaAparte)
                .addGap(115, 115, 115))
        );

        jTabbedPane2.addTab("Notas", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("ID CARRERA :");

        jLabel2.setText("NOMBRE :");

        jLabel3.setText("DESCRIPCIÓN :");

        jLabel4.setText("ID DE CURSO :");

        jLabel5.setText("HORAS POR SEMANA :");

        jLabel6.setText("NOMBRE :");

        txtCursoDescripcion.addActionListener(this::txtCursoDescripcionActionPerformed);

        jLabel7.setText("TELÉFONO :");

        jLabel8.setText("ID PROFESOR :");

        jLabel9.setText("SUELDO :");

        jLabel10.setText("NOMBRE :");

        txtProfesorNombre.addActionListener(this::txtProfesorNombreActionPerformed);

        txtProfesorSueldo.addActionListener(this::txtProfesorSueldoActionPerformed);

        txtProfesorTelefono.addActionListener(this::txtProfesorTelefonoActionPerformed);

        jLabel11.setText("TELÉFONO :");

        jLabel12.setText("ID ALUMNO :");

        jLabel13.setText("DIRECCIÓN :");

        jLabel14.setText("EMAIL :");

        jLabel15.setText("ID SECCIÓN :");

        jLabel16.setText("AULA :");

        txtAlumnoEmail.addActionListener(this::txtAlumnoEmailActionPerformed);

        txtSeccionAula.addActionListener(this::txtSeccionAulaActionPerformed);

        txtSeccionId.addActionListener(this::txtSeccionIdActionPerformed);

        btnRegistrarMatricula.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrarMatricula.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarMatricula.setText("REGISTRAR");
        btnRegistrarMatricula.addActionListener(this::btnRegistrarMatriculaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCursoId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCarreraId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(116, 116, 116))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCursoDescripcion)
                                .addGap(115, 115, 115)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCarreraNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(btnRegistrarMatricula))
                            .addComponent(txtCursoHoras)
                            .addComponent(txtCursoNombre))
                        .addContainerGap(356, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtProfesorId))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtProfesorTelefono))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAlumnoId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSeccionId))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAlumnoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAlumnoDireccion))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtProfesorSueldo))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtProfesorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtAlumnoEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSeccionAula, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(569, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarreraId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtCarreraNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtCursoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCursoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCursoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtCursoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfesorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtProfesorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarMatricula))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfesorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(txtProfesorSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlumnoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlumnoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAlumnoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlumnoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtSeccionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtSeccionAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jTabbedPane2.addTab("Matricula", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCursoDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCursoDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCursoDescripcionActionPerformed

    private void txtProfesorSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfesorSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfesorSueldoActionPerformed

    private void txtProfesorTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfesorTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfesorTelefonoActionPerformed

    private void txtProfesorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfesorNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfesorNombreActionPerformed

    private void txtNotaCursoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaCursoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaCursoNombreActionPerformed

    private void txtNotaAlumnoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaAlumnoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaAlumnoIdActionPerformed

    private void txtAlumnoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlumnoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlumnoEmailActionPerformed

    private void txtSeccionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeccionIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeccionIdActionPerformed

    private void txtSeccionAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeccionAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeccionAulaActionPerformed

    private void btnRegistrarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMatriculaActionPerformed
         try {
    com.mycompany.practicas.Semana4.Universidad.presentation.controller.UniversidadController controlador = 
        new com.mycompany.practicas.Semana4.Universidad.presentation.controller.UniversidadController();
    
    String carreraId = txtCarreraId.getText().trim();
    String carreraNombre = txtCarreraNombre.getText().trim();
    String cursoId = txtCursoId.getText().trim();
    String cursoNombre = txtCursoNombre.getText().trim();
    String cursoDescripcion = txtCursoDescripcion.getText().trim();
    String txtHoras = txtCursoHoras.getText().trim();
    String seccionId = txtSeccionId.getText().trim();
    String seccionAula = txtSeccionAula.getText().trim();
    String profesorId = txtProfesorId.getText().trim();
    String profesorNombre = txtProfesorNombre.getText().trim();
    String profesorTelefono = txtProfesorTelefono.getText().trim();
    String txtSueldo = txtProfesorSueldo.getText().trim();
    String alumnoId = txtAlumnoId.getText().trim();
    String alumnoDireccion = txtAlumnoDireccion.getText().trim();
    String alumnoTelefono = txtAlumnoTelefono.getText().trim();
    String alumnoEmail = txtAlumnoEmail.getText().trim();

    String alumnoNombre = alumnoId; 

    if (carreraId.isEmpty() || carreraNombre.isEmpty() || cursoId.isEmpty() || cursoNombre.isEmpty() ||
        seccionId.isEmpty() || seccionAula.isEmpty() || profesorId.isEmpty() || profesorNombre.isEmpty() ||
        alumnoId.isEmpty() || txtHoras.isEmpty() || txtSueldo.isEmpty()) {
        
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos de la Matrícula.", "Campos Vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int cursoHoras = Integer.parseInt(txtHoras);
    double profesorSueldo = Double.parseDouble(txtSueldo);

    com.mycompany.practicas.Semana4.Universidad.Core.application.Dto.MatriculaDto dto = 
        new com.mycompany.practicas.Semana4.Universidad.Core.application.Dto.MatriculaDto(
            carreraId, carreraNombre, cursoId, cursoNombre, cursoDescripcion, cursoHoras,
            seccionId, seccionAula, profesorId, profesorNombre, profesorTelefono, profesorSueldo,
            alumnoId, alumnoNombre, alumnoDireccion, alumnoTelefono, alumnoEmail
        );

    String reporteFinal = controlador.procesarRegistroMatricula(dto);

    javax.swing.JOptionPane.showMessageDialog(this, reporteFinal, "Matrícula Procesada con Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);

} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Horas y Sueldo deben recibir únicamente caracteres numéricos.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getLocalizedMessage(), "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnRegistrarMatriculaActionPerformed

    private void btnRegistrarNotaAparteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNotaAparteActionPerformed
        try {
    com.mycompany.practicas.Semana4.Universidad.presentation.controller.UniversidadController controlador = 
        new com.mycompany.practicas.Semana4.Universidad.presentation.controller.UniversidadController();

    String aluId = txtNotaAlumnoId.getText().trim();
    String curNombre = txtNotaCursoNombre.getText().trim();
    String profId = txtNotaProfesorId.getText().trim();
    String txtValor = txtNotaValor.getText().trim();

    if (aluId.isEmpty() || curNombre.isEmpty() || profId.isEmpty() || txtValor.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos del módulo de Notas.", "Campos Vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    double notaFinal = Double.parseDouble(txtValor);

    if (notaFinal < 0 || notaFinal > 20) {
        javax.swing.JOptionPane.showMessageDialog(this, "La nota final debe encontrarse en el rango de 0 a 20.", "Nota Inválida", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    com.mycompany.practicas.Semana4.Universidad.Core.application.Dto.RegistrarNotaSeparadaDto dtoNota = 
        new com.mycompany.practicas.Semana4.Universidad.Core.application.Dto.RegistrarNotaSeparadaDto(aluId, curNombre, profId, notaFinal);

    String respuesta = controlador.procesarNotaAparte(dtoNota);
    
    javax.swing.JOptionPane.showMessageDialog(this, respuesta, "Nota Asentada", javax.swing.JOptionPane.INFORMATION_MESSAGE);

} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "El valor de la nota debe ser un número decimal válido.", "Error de Tipo", javax.swing.JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getLocalizedMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnRegistrarNotaAparteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Universidad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarMatricula;
    private javax.swing.JButton btnRegistrarNotaAparte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtAlumnoDireccion;
    private javax.swing.JTextField txtAlumnoEmail;
    private javax.swing.JTextField txtAlumnoId;
    private javax.swing.JTextField txtAlumnoTelefono;
    private javax.swing.JTextField txtCarreraId;
    private javax.swing.JTextField txtCarreraNombre;
    private javax.swing.JTextField txtCursoDescripcion;
    private javax.swing.JTextField txtCursoHoras;
    private javax.swing.JTextField txtCursoId;
    private javax.swing.JTextField txtCursoNombre;
    private javax.swing.JTextField txtNotaAlumnoId;
    private javax.swing.JTextField txtNotaCursoNombre;
    private javax.swing.JTextField txtNotaProfesorId;
    private javax.swing.JTextField txtNotaValor;
    private javax.swing.JTextField txtProfesorId;
    private javax.swing.JTextField txtProfesorNombre;
    private javax.swing.JTextField txtProfesorSueldo;
    private javax.swing.JTextField txtProfesorTelefono;
    private javax.swing.JTextField txtSeccionAula;
    private javax.swing.JTextField txtSeccionId;
    // End of variables declaration//GEN-END:variables
}
