/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicas.Semana4.SistemaSeguridadPolicial.infrastructure.ui;
import com.mycompany.practicas.Semana4.SistemaSeguridadPolicial.infrastructure.Controller.SeguridadController;
import com.mycompany.practicas.Semana4.SistemaSeguridadPolicial.domain.enums.CondicionArma;
import com.mycompany.practicas.Semana4.SistemaSeguridadPolicial.domain.models.Vigilante;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author luisl
 */
public class SistemaSeguridadPolicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SistemaSeguridadPolicial.class.getName());
    private SeguridadController controller = new SeguridadController();
    /**
     * Creates new form SistemaSeguridadPolicial
     */
    public SistemaSeguridadPolicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        for (CondicionArma condicion : CondicionArma.values()) {
            cbxCondicionArma.addItem(condicion.name());   
        }
          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoSucursal = new javax.swing.JTextField();
        txtDomicilioSucursal = new javax.swing.JTextField();
        txtEmpleadosSucursal = new javax.swing.JTextField();
        cbxBancos = new javax.swing.JComboBox<>();
        btnRegistrarSucursal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReporte = new javax.swing.JTextArea();
        btnGenerarReporte = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoBanco = new javax.swing.JTextField();
        txtDomicilioBanco = new javax.swing.JTextField();
        btnRegistrarBanco = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoVigilante = new javax.swing.JTextField();
        txtEdadVigilante = new javax.swing.JTextField();
        btnRegistrarVigilante = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbxVigilantes = new javax.swing.JComboBox<>();
        cbxSucursalesContrato = new javax.swing.JComboBox<>();
        cbxCondicionArma = new javax.swing.JComboBox<>();
        txtFechaContrato = new javax.swing.JTextField();
        btnContratarVigilante = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVigilantes = new javax.swing.JTable();
        btnEliminarVigilante = new javax.swing.JButton();
        btnActualizarVigilante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Código Sucursal:");

        jLabel4.setText("Domicilio:");

        jLabel5.setText("N° de Empleados:");

        jLabel6.setText("Banco Perteneciente:");

        txtCodigoSucursal.addActionListener(this::txtCodigoSucursalActionPerformed);

        cbxBancos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegistrarSucursal.setText("Registrar Sucursal");
        btnRegistrarSucursal.addActionListener(this::btnRegistrarSucursalActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoSucursal)
                            .addComponent(txtDomicilioSucursal)
                            .addComponent(txtEmpleadosSucursal)
                            .addComponent(cbxBancos, 0, 97, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnRegistrarSucursal)))
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigoSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDomicilioSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmpleadosSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnRegistrarSucursal)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestion de sucursales", jPanel2);

        txtAreaReporte.setEditable(false);
        txtAreaReporte.setColumns(20);
        txtAreaReporte.setRows(5);
        jScrollPane1.setViewportView(txtAreaReporte);

        btnGenerarReporte.setText("Generar Reporte Policial");
        btnGenerarReporte.addActionListener(this::btnGenerarReporteActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerarReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGenerarReporte))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", jPanel3);

        jLabel1.setText("Codigo de banco:");

        jLabel2.setText("Domicilio:");

        txtDomicilioBanco.addActionListener(this::txtDomicilioBancoActionPerformed);

        btnRegistrarBanco.setText("Registrar banco");
        btnRegistrarBanco.addActionListener(this::btnRegistrarBancoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnRegistrarBanco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(txtCodigoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(txtDomicilioBanco)))))
                .addGap(25, 436, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtDomicilioBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addComponent(btnRegistrarBanco)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestion de bancos", jPanel1);

        jLabel7.setText("Código Vigilante:");

        jLabel8.setText("Edad:");

        btnRegistrarVigilante.setText("Registrar Vigilante");
        btnRegistrarVigilante.addActionListener(this::btnRegistrarVigilanteActionPerformed);

        jLabel9.setText("Seccion vigilantes");

        jLabel10.setText("Seccion Contratos");

        jLabel11.setText("Seleccionar Vigilante:");

        jLabel12.setText("Seleccionar Sucursal:");

        jLabel13.setText("Fecha (DD/MM/AAAA):");

        jLabel14.setText("Condición:");

        cbxVigilantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxSucursalesContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxCondicionArma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnContratarVigilante.setText("Asignar a Sucursal");
        btnContratarVigilante.addActionListener(this::btnContratarVigilanteActionPerformed);

        tblVigilantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Edad"
            }
        ));
        jScrollPane3.setViewportView(tblVigilantes);

        btnEliminarVigilante.setText("Eliminar");
        btnEliminarVigilante.addActionListener(this::btnEliminarVigilanteActionPerformed);

        btnActualizarVigilante.setText("Actualizar");
        btnActualizarVigilante.addActionListener(this::btnActualizarVigilanteActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigoVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdadVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnRegistrarVigilante)))
                .addGap(91, 91, 91)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(31, 31, 31)
                        .addComponent(txtFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnContratarVigilante)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSucursalesContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxCondicionArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxVigilantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarVigilante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizarVigilante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxVigilantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtCodigoVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxSucursalesContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(cbxCondicionArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizarVigilante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarVigilante, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEdadVigilante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(txtFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarVigilante)
                            .addComponent(btnContratarVigilante))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Vigilantes y Contratos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContratarVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratarVigilanteActionPerformed
        // TODO add your handling code here:
        Object vigilanteSel = cbxVigilantes.getSelectedItem();
        Object sucursalSel = cbxSucursalesContrato.getSelectedItem();
        String fecha = txtFechaContrato.getText();
        Object condicionSel = cbxCondicionArma.getSelectedItem();

        if (vigilanteSel == null || sucursalSel == null || fecha.trim().isEmpty() || condicionSel == null) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos de la asignación.");
            return;
        }

        String codVigilante = vigilanteSel.toString();
        String codSucursal = sucursalSel.toString();
        CondicionArma condicion = CondicionArma.valueOf(condicionSel.toString());

        controller.contratarVigilante(codVigilante, codSucursal, fecha, condicion);
        JOptionPane.showMessageDialog(this, "Vigilante asignado exitosamente a la sucursal.");
        txtFechaContrato.setText("");
    }//GEN-LAST:event_btnContratarVigilanteActionPerformed

    private void btnRegistrarVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVigilanteActionPerformed

        String codigo = txtCodigoVigilante.getText();
        String edadStr = txtEdadVigilante.getText();

        if (codigo.trim().isEmpty() || edadStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos del vigilante.");
            return;
        }

        try {
            int edad = Integer.parseInt(edadStr);
            
            
            boolean guardadoConExito = controller.registrarVigilante(codigo, edad);

           
            if (guardadoConExito) {
                
                JOptionPane.showMessageDialog(this, "Vigilante registrado con éxito.");
                
                cbxVigilantes.addItem(codigo);
                actualizarTablaVigilantes();   
                
                txtCodigoVigilante.setText("");
                txtEdadVigilante.setText("");
            } else {
                
                JOptionPane.showMessageDialog(this, "Error: El código de vigilante YA EXISTE.", "Código Duplicado", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La edad debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnRegistrarVigilanteActionPerformed

    private void btnRegistrarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarBancoActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoBanco.getText();
        String domicilio = txtDomicilioBanco.getText();

        if (codigo.trim().isEmpty() || domicilio.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos del banco.");
            return;
        }

        controller.registrarBanco(codigo, domicilio);
        JOptionPane.showMessageDialog(this, "Banco registrado con éxito.");

        cbxBancos.addItem(codigo);

        txtCodigoBanco.setText("");
        txtDomicilioBanco.setText("");
    }//GEN-LAST:event_btnRegistrarBancoActionPerformed

    private void txtDomicilioBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioBancoActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:

        String reporte = controller.generarReportePolicial();

        txtAreaReporte.setText(reporte);
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnRegistrarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSucursalActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodigoSucursal.getText();
        String domicilio = txtDomicilioSucursal.getText();
        String empleadosStr = txtEmpleadosSucursal.getText();

        Object bancoSeleccionado = cbxBancos.getSelectedItem();

        if (codigo.trim().isEmpty() || domicilio.trim().isEmpty() || empleadosStr.trim().isEmpty() || bancoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos y seleccione un banco.");
            return;
        }

        try {
            int empleados = Integer.parseInt(empleadosStr);
            String codigoBanco = bancoSeleccionado.toString();

            controller.registrarSucursal(codigo, domicilio, empleados, codigoBanco);
            JOptionPane.showMessageDialog(this, "Sucursal registrada con éxito.");
            cbxSucursalesContrato.addItem(codigo);

            txtCodigoSucursal.setText("");
            txtDomicilioSucursal.setText("");
            txtEmpleadosSucursal.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El número de empleados debe ser un valor numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarSucursalActionPerformed

    private void txtCodigoSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoSucursalActionPerformed

    private void btnEliminarVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVigilanteActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblVigilantes.getSelectedRow();

        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un vigilante de la tabla para eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
       
        String codigo = tblVigilantes.getValueAt(filaSeleccionada, 0).toString();

        
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar al vigilante " + codigo + "?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            
           
            boolean eliminado = controller.eliminarVigilante(codigo);
            
            if (eliminado) {
               
                cbxVigilantes.removeItem(codigo);
                
                
                actualizarTablaVigilantes();
                
                JOptionPane.showMessageDialog(this, "Vigilante eliminado con éxito.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar. No se encontró el vigilante.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarVigilanteActionPerformed

    private void btnActualizarVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarVigilanteActionPerformed
        // TODO add your handling code here:
        
        int filaSeleccionada = tblVigilantes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un vigilante de la tabla para actualizar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        String codigo = tblVigilantes.getValueAt(filaSeleccionada, 0).toString();
        
        
        String nuevaEdadStr = txtEdadVigilante.getText();

        if (nuevaEdadStr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, escriba la nueva edad en el cuadro de texto.");
            return;
        }

        try {
            int nuevaEdad = Integer.parseInt(nuevaEdadStr);
            
           
            boolean actualizado = controller.actualizarVigilante(codigo, nuevaEdad);
            
            if (actualizado) {
                JOptionPane.showMessageDialog(this, "Vigilante actualizado con éxito.");
                actualizarTablaVigilantes(); // Refrescamos la tabla para ver la nueva edad
                
                txtCodigoVigilante.setText("");
                txtEdadVigilante.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar. Vigilante no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La edad debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarVigilanteActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SistemaSeguridadPolicial().setVisible(true));
    }
    
    private void actualizarTablaVigilantes() {
    
    DefaultTableModel modelo = (DefaultTableModel) tblVigilantes.getModel();
    
    
    modelo.setRowCount(0);
    
    
    for (Vigilante v : controller.getVigilantes()) {
        
        modelo.addRow(new Object[]{
            v.getCodigo(),
            v.getEdad()
        });
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarVigilante;
    private javax.swing.JButton btnContratarVigilante;
    private javax.swing.JButton btnEliminarVigilante;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnRegistrarBanco;
    private javax.swing.JButton btnRegistrarSucursal;
    private javax.swing.JButton btnRegistrarVigilante;
    private javax.swing.JComboBox<String> cbxBancos;
    private javax.swing.JComboBox<String> cbxCondicionArma;
    private javax.swing.JComboBox<String> cbxSucursalesContrato;
    private javax.swing.JComboBox<String> cbxVigilantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblVigilantes;
    private javax.swing.JTextArea txtAreaReporte;
    private javax.swing.JTextField txtCodigoBanco;
    private javax.swing.JTextField txtCodigoSucursal;
    private javax.swing.JTextField txtCodigoVigilante;
    private javax.swing.JTextField txtDomicilioBanco;
    private javax.swing.JTextField txtDomicilioSucursal;
    private javax.swing.JTextField txtEdadVigilante;
    private javax.swing.JTextField txtEmpleadosSucursal;
    private javax.swing.JTextField txtFechaContrato;
    // End of variables declaration//GEN-END:variables
}
