/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicas.semana5.agroalimentaria.infrastructure.ui;

/**
 *
 * @author USER
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miProductoCongelado = new javax.swing.JMenuItem();
        miProductoFresco = new javax.swing.JMenuItem();
        miProductoRefrigerado = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        jMenu1.setText("Productos");

        miProductoCongelado.setText("Producto Congelado");
        miProductoCongelado.addActionListener(this::miProductoCongeladoActionPerformed);
        jMenu1.add(miProductoCongelado);

        miProductoFresco.setText("Producto Fresco");
        miProductoFresco.addActionListener(this::miProductoFrescoActionPerformed);
        jMenu1.add(miProductoFresco);

        miProductoRefrigerado.setText("Producto Refrigerado");
        miProductoRefrigerado.addActionListener(this::miProductoRefrigeradoActionPerformed);
        jMenu1.add(miProductoRefrigerado);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProductoCongeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductoCongeladoActionPerformed
        // TODO add your handling code here:
        new FrmProductoCongelado().setVisible(true);
    }//GEN-LAST:event_miProductoCongeladoActionPerformed

    private void miProductoFrescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductoFrescoActionPerformed
        // TODO add your handling code here:
        new FrmProductoFresco().setVisible(true);
    }//GEN-LAST:event_miProductoFrescoActionPerformed

    private void miProductoRefrigeradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductoRefrigeradoActionPerformed
        // TODO add your handling code here:
        new FrmProductoRefrigerado().setVisible(true);
    }//GEN-LAST:event_miProductoRefrigeradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miProductoCongelado;
    private javax.swing.JMenuItem miProductoFresco;
    private javax.swing.JMenuItem miProductoRefrigerado;
    // End of variables declaration//GEN-END:variables
}
