/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicas.Semana4.Olimpiada.presentation.ui;
import java.util.ArrayList;
import java.util.List;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.Duration;
import java.util.Calendar;
import com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.Sede;
import com.mycompany.practicas.Semana4.Olimpiada.core.domain.enums.ComisarioRol;

import com.mycompany.practicas.Semana4.Olimpiada.presentation.controller.EventoController;
import com.mycompany.practicas.Semana4.Olimpiada.core.application.Dto.*;
import com.mycompany.practicas.Semana4.Olimpiada.infrastructure.id.UUIDGenerator;
import javax.swing.JOptionPane;
import com.mycompany.practicas.Semana4.Olimpiada.core.application.usecases.IdGeneradorUseCase;
import com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.*;

/**
 *
 * @author AUGUSTO RODRIGUEZ
 */
public class Olimpiada extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Olimpiada.class.getName());
    
    private final IdGeneradorUseCase UUIDGenerador;
    private List<Participacion> tempComisarios = new ArrayList();
   
    
    private List<Comisario> comisariosSeleccionadosEvento = new ArrayList();
    
    //Estos atributos es para crear la sede de comisarios en 
    private List<Complejo> selectComplejosSede = new ArrayList();
    //Estos atributos es para crear el complejo de comisarios en 
    private List<Evento> selectEventosComplejo = new ArrayList();
    private List<Area> selectAreasComplejo = new ArrayList();  
    //Este atributo es para crear la participacion de comisarios en 
    //btnAddComisarioActionPerformed() :DDD
    private List<Participacion> partiComisarioCrearEvento = new ArrayList();
    private String uuidEventoCreating = null;
    
    public Olimpiada() {
       initComponents();
       this.UUIDGenerador = new IdGeneradorUseCase(new UUIDGenerator());
        cbxRolComisario.removeAllItems();
        for (ComisarioRol rol : ComisarioRol.values()) {
            cbxRolComisario.addItem(rol);
        }
    }
 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label36 = new java.awt.Label();
        label35 = new java.awt.Label();
        btnCrearComplejo1 = new javax.swing.JButton();
        cbxSelecAreasComplejo1 = new javax.swing.JComboBox<>();
        label30 = new java.awt.Label();
        btnAreasComplejo1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        txtNombreSede = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        cbxListComplejosSede = new javax.swing.JComboBox<>();
        btnAddSede = new javax.swing.JButton();
        lstComplejosSede = new java.awt.List();
        label4 = new java.awt.Label();
        txtPresupuestoSede = new javax.swing.JTextField();
        btnCrearSede = new javax.swing.JButton();
        lstSedesCreadas = new java.awt.List();
        label5 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        txtNombreComisario = new javax.swing.JTextField();
        btnCrearComisario = new javax.swing.JButton();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        btnEliminar = new javax.swing.JButton();
        cbxComisarios = new javax.swing.JComboBox<>();
        label27 = new java.awt.Label();
        cbxComisariosMostrar = new javax.swing.JComboBox<>();
        btnComisariosMostrar = new javax.swing.JButton();
        lblParticipacionesComisario = new java.awt.Label();
        lstComisariosParticipaciones = new java.awt.List();
        label31 = new java.awt.Label();
        txtApellidoComisario = new javax.swing.JTextField();
        label32 = new java.awt.Label();
        jPanel5 = new javax.swing.JPanel();
        label21 = new java.awt.Label();
        label22 = new java.awt.Label();
        caFinalEvento = new com.toedter.calendar.JCalendar();
        label23 = new java.awt.Label();
        caInicioEvento = new com.toedter.calendar.JCalendar();
        label24 = new java.awt.Label();
        txtNumParticipantes = new javax.swing.JTextField();
        label25 = new java.awt.Label();
        cbxEventoComsiarios = new javax.swing.JComboBox<>();
        btnCrearEvento = new javax.swing.JButton();
        cbxRolComisario = new javax.swing.JComboBox<>();
        label26 = new java.awt.Label();
        btnAddComisario = new javax.swing.JButton();
        lstComisariosSeleccionados = new java.awt.List();
        label33 = new java.awt.Label();
        txtEventoTitle = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnCrearArea = new javax.swing.JButton();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        txtLocalizacionArea = new javax.swing.JTextField();
        label15 = new java.awt.Label();
        txtDescripcionArea = new javax.swing.JTextField();
        label28 = new java.awt.Label();
        btnEliminarArea = new javax.swing.JButton();
        cbxAreasEliminar = new javax.swing.JComboBox<>();
        txtNombreArea = new javax.swing.JTextField();
        label29 = new java.awt.Label();
        lstAreasLista = new java.awt.List();
        jPanel2 = new javax.swing.JPanel();
        label7 = new java.awt.Label();
        txtNombreComplejo = new javax.swing.JTextField();
        label8 = new java.awt.Label();
        txtLocalizacionComplejo = new javax.swing.JTextField();
        label9 = new java.awt.Label();
        txtJefeIndividualComplejo = new javax.swing.JTextField();
        cbxSelecAreasComplejo = new javax.swing.JComboBox<>();
        btnAreasComplejo = new javax.swing.JButton();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        cbxSelecEventosComplejo = new javax.swing.JComboBox<>();
        btnAddEventoComplejo = new javax.swing.JButton();
        lstSelecEventosComplejo = new java.awt.List();
        label18 = new java.awt.Label();
        btnCrearComplejo = new javax.swing.JButton();
        lstSelectAreasComplejo = new java.awt.List();
        lstComplejosCreados = new java.awt.List();
        label34 = new java.awt.Label();
        label37 = new java.awt.Label();
        btnEliminarComplejo = new javax.swing.JButton();
        cbxSelecComplejoEliminar = new javax.swing.JComboBox<>();
        label38 = new java.awt.Label();
        label39 = new java.awt.Label();

        label36.setText("!CUIDADO! Si eliminas un complejo eliminará automaticamente las\n");

        label35.setText("Ingresa el nombre de un jefe de organización individual");

        btnCrearComplejo1.setText("Crear Complejo");
        btnCrearComplejo1.setActionCommand("");
        btnCrearComplejo1.addActionListener(this::btnCrearComplejo1ActionPerformed);

        label30.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label30.setText("Complejos creados");

        btnAreasComplejo1.setText("+");
        btnAreasComplejo1.addActionListener(this::btnAreasComplejo1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(this::jTabbedPane1StateChanged);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label1.setText("Sedes existentes");

        txtNombreSede.setText("EjemploSede");

        label2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label2.setText("Ingresa el presupuesto");

        label3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label3.setText("Asigna complejos a la sede:");

        btnAddSede.setBackground(new java.awt.Color(0, 153, 255));
        btnAddSede.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSede.setText("+");
        btnAddSede.addActionListener(this::btnAddSedeActionPerformed);

        label4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label4.setText("Ingresa el nombre de la sede a crear");

        txtPresupuestoSede.setText("EjemploSede");

        btnCrearSede.setBackground(new java.awt.Color(0, 153, 255));
        btnCrearSede.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearSede.setText("Crear Sede");
        btnCrearSede.setActionCommand("");
        btnCrearSede.addActionListener(this::btnCrearSedeActionPerformed);

        label5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label5.setText("Crea sede");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPresupuestoSede, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lstComplejosSede, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbxListComplejosSede, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAddSede, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnCrearSede, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstSedesCreadas, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPresupuestoSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxListComplejosSede, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddSede, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearSede)
                        .addGap(56, 56, 56)
                        .addComponent(lstComplejosSede, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lstSedesCreadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab(" Sedes", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        label16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label16.setText("Crear Comisario");

        label17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label17.setText("Ingresa el nombre del comisario");

        txtNombreComisario.setText("Juarez");

        btnCrearComisario.setBackground(new java.awt.Color(51, 153, 255));
        btnCrearComisario.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearComisario.setText("Crear Comisario");
        btnCrearComisario.addActionListener(this::btnCrearComisarioActionPerformed);

        label19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label19.setText("Eliminar Comisario");

        label20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label20.setText("Selecciona el comisario a eliminar");

        btnEliminar.setBackground(new java.awt.Color(255, 204, 204));
        btnEliminar.setForeground(new java.awt.Color(255, 51, 51));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        label27.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label27.setText("Información");

        btnComisariosMostrar.setBackground(new java.awt.Color(0, 153, 255));
        btnComisariosMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnComisariosMostrar.setText("Mostrar");
        btnComisariosMostrar.setBorderPainted(false);
        btnComisariosMostrar.addActionListener(this::btnComisariosMostrarActionPerformed);

        lblParticipacionesComisario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblParticipacionesComisario.setText("Comisario: 0 | participaciones: 0");

        label31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label31.setText("Selecciona el comisario a mostrar toda su informacion y participación");

        txtApellidoComisario.setText("Pinillos del Carmen");

        label32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label32.setText("Ingresa los apellidos del comisario");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbxComisarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEliminar))))
                            .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoComisario, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreComisario, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnCrearComisario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbxComisariosMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnComisariosMostrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(label31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblParticipacionesComisario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lstComisariosParticipaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblParticipacionesComisario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreComisario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxComisariosMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComisariosMostrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtApellidoComisario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCrearComisario)
                        .addGap(36, 36, 36)
                        .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxComisarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar)))
                    .addComponent(lstComisariosParticipaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        lblParticipacionesComisario.getAccessibleContext().setAccessibleName("Comisario: participaciones:");

        jTabbedPane1.addTab("Comisario", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        label21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label21.setText("Crear Evento");

        label22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label22.setText("Ingresa la fecha del evento");

        label23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label23.setText("Ingrese cuando termina evento");

        label24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label24.setText("Ingresa números de participantes");

        txtNumParticipantes.setText("2");

        label25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label25.setText("Selecciona el comisario");

        cbxEventoComsiarios.setBorder(null);
        cbxEventoComsiarios.addActionListener(this::cbxEventoComsiariosActionPerformed);

        btnCrearEvento.setBackground(new java.awt.Color(0, 153, 255));
        btnCrearEvento.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearEvento.setText("Crear Evento");
        btnCrearEvento.addActionListener(this::btnCrearEventoActionPerformed);

        cbxRolComisario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        label26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label26.setText("Secciona el rol");

        btnAddComisario.setBackground(new java.awt.Color(0, 153, 255));
        btnAddComisario.setForeground(new java.awt.Color(255, 255, 255));
        btnAddComisario.setText("+");
        btnAddComisario.addActionListener(this::btnAddComisarioActionPerformed);

        label33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label33.setText("Ingresa título de evento");

        txtEventoTitle.setText("2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caInicioEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caFinalEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxRolComisario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(93, 93, 93))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxEventoComsiarios, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addComponent(btnAddComisario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lstComisariosSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEventoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnCrearEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(210, 210, 210))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(caInicioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caFinalEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(240, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEventoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxRolComisario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxEventoComsiarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddComisario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lstComisariosSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btnCrearEvento)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Evento", jPanel5);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnCrearArea.setBackground(new java.awt.Color(0, 153, 255));
        btnCrearArea.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearArea.setText("Crear Área");
        btnCrearArea.addActionListener(this::btnCrearAreaActionPerformed);

        label12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label12.setText("Áreas a eliminar");

        label13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label13.setText("Ingresa la descripción del área");

        label14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label14.setText("Ingresar área");

        txtLocalizacionArea.setText("Av América");

        label15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label15.setText("Áreas creadas");

        txtDescripcionArea.setText("Una área para...");

        label28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label28.setText("Crear Área");

        btnEliminarArea.setBackground(new java.awt.Color(255, 204, 204));
        btnEliminarArea.setForeground(new java.awt.Color(255, 51, 51));
        btnEliminarArea.setText("Eliminar Área");
        btnEliminarArea.addActionListener(this::btnEliminarAreaActionPerformed);

        txtNombreArea.setText("Area 1");
        txtNombreArea.addActionListener(this::txtNombreAreaActionPerformed);

        label29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label29.setText("Ingresa la localización del área");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxAreasEliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDescripcionArea, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLocalizacionArea)
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombreArea)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(btnCrearArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnEliminarArea)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstAreasLista, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstAreasLista, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtLocalizacionArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescripcionArea, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnCrearArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxAreasEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnEliminarArea)
                .addGap(116, 116, 116))
        );

        label12.getAccessibleContext().setAccessibleName("Áreas a eliminar");
        label14.getAccessibleContext().setAccessibleName("Ingresa nombre del área");

        jTabbedPane1.addTab("Área", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        label7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label7.setText("Ingresa el nombre del complejo a crear:");

        txtNombreComplejo.setText("Ejemplocomplejo");
        txtNombreComplejo.addActionListener(this::txtNombreComplejoActionPerformed);

        label8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label8.setText("Ingresa la localización del complejo a crear:");

        txtLocalizacionComplejo.setText("Av. ...");
        txtLocalizacionComplejo.addActionListener(this::txtLocalizacionComplejoActionPerformed);

        label9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label9.setText("Ingresa el nombre de un jefe de organización individual");

        txtJefeIndividualComplejo.setText("Ejemplocomplejo");
        txtJefeIndividualComplejo.addActionListener(this::txtJefeIndividualComplejoActionPerformed);

        btnAreasComplejo.setBackground(new java.awt.Color(0, 153, 255));
        btnAreasComplejo.setForeground(new java.awt.Color(255, 255, 255));
        btnAreasComplejo.setText("+");
        btnAreasComplejo.addActionListener(this::btnAreasComplejoActionPerformed);

        label10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label10.setText("Asigna las áreas a ocupar");

        label11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label11.setText("Crea complejo");

        btnAddEventoComplejo.setBackground(new java.awt.Color(0, 153, 255));
        btnAddEventoComplejo.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEventoComplejo.setText("+");
        btnAddEventoComplejo.addActionListener(this::btnAddEventoComplejoActionPerformed);

        label18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label18.setText("Selecciona eventos");

        btnCrearComplejo.setBackground(new java.awt.Color(0, 153, 255));
        btnCrearComplejo.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearComplejo.setText("Crear Complejo");
        btnCrearComplejo.setActionCommand("");
        btnCrearComplejo.addActionListener(this::btnCrearComplejoActionPerformed);

        label34.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label34.setText("Complejos creados");

        label37.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label37.setText("EliminarComplejo");

        btnEliminarComplejo.setBackground(new java.awt.Color(255, 204, 204));
        btnEliminarComplejo.setForeground(new java.awt.Color(255, 102, 102));
        btnEliminarComplejo.setText("Eliminar");
        btnEliminarComplejo.addActionListener(this::btnEliminarComplejoActionPerformed);

        label38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label38.setForeground(new java.awt.Color(255, 0, 51));
        label38.setText("CUIDADO si eliminas un Complejo eliminas también las áreas que\n");

        label39.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label39.setForeground(new java.awt.Color(255, 0, 51));
        label39.setText("contiene dentro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(cbxSelecAreasComplejo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAreasComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombreComplejo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLocalizacionComplejo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(cbxSelecEventosComplejo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddEventoComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJefeIndividualComplejo)
                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstSelecEventosComplejo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lstSelectAreasComplejo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label37, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label38, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbxSelecComplejoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label39, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstComplejosCreados, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnCrearComplejo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJefeIndividualComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocalizacionComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lstComplejosCreados, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSelecEventosComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddEventoComplejo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(label37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSelecComplejoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarComplejo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lstSelecEventosComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(label38, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(label39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSelecAreasComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAreasComplejo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstSelectAreasComplejo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearComplejo)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Complejo", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSedeActionPerformed
        String nombreSede = txtNombreSede.getText();     
        String presupuestoSede = txtPresupuestoSede.getText();
        String uuid = this.UUIDGenerador.generar();
        
        if (nombreSede.isBlank() || nombreSede.isBlank()) {
             JOptionPane.showMessageDialog(
                null,
                "Debes rellenar todos los campos para crear una Sede",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        double presupuesto = 0.0;
        try {
            presupuesto = Double.parseDouble(presupuestoSede);
    
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                null,
                "El presupeusto ingresado no es válido",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        if (selectComplejosSede.isEmpty()) {
            JOptionPane.showMessageDialog(
                null,
                "debes seleccionar uno o más complejos.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        EventoController.crearSede(new Sede(uuid, presupuesto, selectComplejosSede, nombreSede));
        selectComplejosSede.clear();
        lstComplejosSede.removeAll();
        lstSedesCreadas.add("Nombre: "+nombreSede+" | Complejos: "+selectComplejosSede.size() );
    }//GEN-LAST:event_btnCrearSedeActionPerformed

    private void btnAddSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSedeActionPerformed
        if (cbxListComplejosSede.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(
                null,
                "Debes seleccionar al menos un complejo",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }      
        
        Complejo com = (Complejo) cbxListComplejosSede.getSelectedItem();


        if (selectComplejosSede.contains(com))return;
        
        selectComplejosSede.add(com);
        lstComplejosSede.add(com.getNombre());
    }//GEN-LAST:event_btnAddSedeActionPerformed

    private void btnCrearComisarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearComisarioActionPerformed
        String nombre = txtNombreComisario.getText();
        String apellido = txtApellidoComisario.getText();
        String uuid = this.UUIDGenerador.generar();
        
        if (nombre == null || nombre.isBlank()) {
            JOptionPane.showMessageDialog(
                null,
                "El nombre del Comisario no fue igresado",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        if (apellido == null || apellido.isBlank()) {
            JOptionPane.showMessageDialog(
                null,
                "El apellido del Comisario no fue igresado",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        String creadoMensaje = EventoController.crearComisario(new Comisario(uuid, nombre));
        if (creadoMensaje != null) {
            JOptionPane.showMessageDialog(
                null,
                creadoMensaje,
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        reloadAllUIComisarios();
        JOptionPane.showMessageDialog(null, "Se creó con éxito el comisario" + nombre + " con uuid " + uuid);
    }//GEN-LAST:event_btnCrearComisarioActionPerformed
    private void reloadAllUIComisarios(){
        
        List<Comisario> temComisarios = EventoController.getComisarios().getItems();
        cbxComisarios.removeAllItems(); 
        cbxComisariosMostrar.removeAllItems();
        cbxEventoComsiarios.removeAllItems();
        for (Comisario comisario : temComisarios) {
            cbxComisarios.addItem(comisario);
            cbxComisariosMostrar.addItem(comisario);
            cbxEventoComsiarios.addItem(comisario);
        }
        
    }
    private void btnCrearAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAreaActionPerformed
        String desArea = txtDescripcionArea.getText();
        String locArea = txtLocalizacionArea.getText();
        String nomArea = txtNombreArea.getText();
        String uuid = this.UUIDGenerador.generar();
        
        if (desArea.isBlank() || locArea.isBlank() || nomArea.isBlank()) {
            JOptionPane.showMessageDialog(
                null,
                "Debes rellenar todos los campos para crear un área",
                "Evento creado",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        List<Area> areas = EventoController.crearArea(new AreaDto(uuid, desArea,locArea, nomArea));
        
        if (areas == null) {
            JOptionPane.showMessageDialog(
                null,
                "E área que intenta crear tiene el mismo nombre o misma ubicación",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return; 
        }
        cbxAreasEliminar.removeAllItems();
        lstAreasLista.removeAll();
        for (Area a : areas) {
            cbxAreasEliminar.addItem(a);
            lstAreasLista.add(a.toString());
        }
        JOptionPane.showMessageDialog(null, "Se creó el Área " + locArea);
    }//GEN-LAST:event_btnCrearAreaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
        if (cbxComisarios.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(
                null,
                "Debe seleccionar un comisario",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        Comisario seleccionado = (Comisario) cbxComisarios.getSelectedItem();
        EventoController.eliminarComisario(seleccionado.getUUID());
        reloadAllUIComisarios();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCrearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEventoActionPerformed
               
        if (partiComisarioCrearEvento.isEmpty() || uuidEventoCreating == null) {
            JOptionPane.showMessageDialog(
                null,
                "Debe asignar al menos un comisario a este evento.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        String nParticipantes = txtNumParticipantes.getText();
        String eventoTitle = txtEventoTitle.getText();
        if (nParticipantes.isBlank() || eventoTitle.isBlank()) {
            JOptionPane.showMessageDialog(
                null,
                "debe ingresar el núemro de participantes",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return; 
        }
        
        int numeroParticipantes = 0;
        try{
            numeroParticipantes = Integer.parseInt(nParticipantes);
        }catch(Exception e){
           JOptionPane.showMessageDialog(
                null,
                e,
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return; 
        }
        
        Calendar calInicio = caInicioEvento.getCalendar(); 
        Calendar calFinal = caFinalEvento.getCalendar();
        if (calInicio == null || calFinal == null){
            JOptionPane.showMessageDialog(
                null,
                "Debe asignar una fecha de inicio y final del evento",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
            
        LocalDateTime inicio = calInicio.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        LocalDateTime fin = calFinal.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        
        Duration diferencia = Duration.between(inicio, fin);
        
        long minutosTotales = diferencia.toMinutes(); 
        
        //Gente aqui ya tenemos  minutosTotales, inicio, fin, nParticipantes, 
        //partiComisarioCrearEvento, uuidEventoCreating.
        //Priemro asignar a comisario las participaciones.
        
        List<Comisario> comisarios = EventoController.addParticipacionComisario(partiComisarioCrearEvento);
        if (comisarios == null) {
            JOptionPane.showMessageDialog(
                null,
                "No se ´pudo obtener la lisat de comisarios actualizada para el evento",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        EventoController.crearEvento(new Evento(eventoTitle, uuidEventoCreating, inicio, fin,  minutosTotales, numeroParticipantes, comisarios));
        
        lstComisariosSeleccionados.removeAll();
        tempComisarios.clear();
        uuidEventoCreating = null;
        txtNumParticipantes.setText("");
        partiComisarioCrearEvento.clear();
        uuidEventoCreating = "";
        JOptionPane.showMessageDialog(
                null,
                "Se creó con éxito el evento" + uuidEventoCreating);
        
        
    }//GEN-LAST:event_btnCrearEventoActionPerformed

    private void cbxEventoComsiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEventoComsiariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEventoComsiariosActionPerformed

    private void btnAddComisarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddComisarioActionPerformed
        
        
        if (cbxEventoComsiarios.getSelectedIndex() == -1 || cbxRolComisario.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(
                null,
                "Debe seleccionar un comisario con su respectivo rol",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        Comisario comisario = (Comisario) cbxEventoComsiarios.getSelectedItem();
        ComisarioRol rol = (ComisarioRol) cbxRolComisario.getSelectedItem();
        String idEvento = this.UUIDGenerador.generar();
        
        var newParti = new Participacion(rol, idEvento, comisario);
        
        if (partiComisarioCrearEvento.contains(newParti)) {
            return;
        }    
        partiComisarioCrearEvento.add(newParti); //diferentes comisarios e
        uuidEventoCreating = idEvento;
        lstComisariosSeleccionados.add("Comisario: "+ comisario.getNombre() + " Rol: " + rol.getRol());
        
    }//GEN-LAST:event_btnAddComisarioActionPerformed

    private void txtNombreComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreComplejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreComplejoActionPerformed

    private void txtLocalizacionComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalizacionComplejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalizacionComplejoActionPerformed

    private void btnCrearComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearComplejoActionPerformed
        String jefeIndividual = txtJefeIndividualComplejo.getText();
        String localizacionComplejo = txtLocalizacionComplejo.getText();
        String nombreComplejo = txtNombreComplejo.getText();
        String uuid = this.UUIDGenerador.generar();
        
        if (jefeIndividual.isBlank() || localizacionComplejo.isBlank() || nombreComplejo.isBlank()) {
            JOptionPane.showMessageDialog(
                null,
                "Debes rellenar todos los campos.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
       
        if (selectAreasComplejo.isEmpty() || selectEventosComplejo.isEmpty()) {
            JOptionPane.showMessageDialog(
                null,
                "debes seleccionar al menos un área o evento.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        Complejo com = new Complejo(
                        nombreComplejo,
                        uuid,
                        localizacionComplejo,
                        jefeIndividual,
                        selectAreasComplejo,
                        selectEventosComplejo);     
        
        EventoController.crearComplejo(com);
                   
        
        
        selectAreasComplejo.clear();
        selectEventosComplejo.clear();
        lstSelectAreasComplejo.removeAll();
        lstSelecEventosComplejo.removeAll();
        
        lstComplejosCreados.add("Nombre: "+nombreComplejo+" Localizacion: "+ localizacionComplejo );
        cbxSelecComplejoEliminar.addItem(com);
        JOptionPane.showMessageDialog(null, "Se creò con èxito el complejo: " + nombreComplejo);
    }//GEN-LAST:event_btnCrearComplejoActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        
        List<Evento> tempEvento = EventoController.getEventos().getItems();
        
        cbxSelecEventosComplejo.removeAllItems();
        
        for (Evento evn : tempEvento) {
            cbxSelecEventosComplejo.addItem(evn);
        }
        
        List<Area> tempArea = EventoController.getAreas().getItems();
        
        cbxSelecAreasComplejo.removeAllItems();
        
        for (Area ar : tempArea) {
            cbxSelecAreasComplejo.addItem(ar);
        }

        List<Complejo> tempComplej = EventoController.getComplejos().getItems();
        
        cbxListComplejosSede.removeAllItems();
        
        for (Complejo c : tempComplej) {
            cbxListComplejosSede.addItem(c);
        }
        
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnAddEventoComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventoComplejoActionPerformed
        if (cbxSelecEventosComplejo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(
                null,
                "Debes seleccionar al menos un evento para agregar",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        Evento evn = (Evento) cbxSelecEventosComplejo.getSelectedItem();
        if (!selectEventosComplejo.contains(evn)) {
            selectEventosComplejo.add(evn);
            lstSelecEventosComplejo.add(evn.toString());
        }
    }//GEN-LAST:event_btnAddEventoComplejoActionPerformed

    private void btnAreasComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreasComplejoActionPerformed
        if (cbxSelecAreasComplejo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(
                null,
                "Debes seleccionar al menos un evento para agregar",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        Area narea = (Area)cbxSelecAreasComplejo.getSelectedItem();
        if (!selectAreasComplejo.contains(narea)) {
            selectAreasComplejo.add(narea);
            lstSelectAreasComplejo.add(narea.getLocalizacion());
        }
    }//GEN-LAST:event_btnAreasComplejoActionPerformed

    private void btnComisariosMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComisariosMostrarActionPerformed
        if (cbxComisariosMostrar.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(
                null,
                "Debes seleccionar al menos un comisario",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        Comisario com = (Comisario)cbxComisariosMostrar.getSelectedItem();
        List<Participacion> participaciones = com.getParticipaciones();
        
        if (participaciones == null) return;
        
        lblParticipacionesComisario.setText(
                "Comisario: " + com.getNombre() + " | participaciones: 0"  + participaciones.size());
        for (Participacion p : participaciones) {            
            Comisario c = p.getComisarioParticipacion();            
            lstComisariosParticipaciones.add("Nombre comisario: " + c.getNombre() + " | rol: " + p.getRol() + " | UUID Evento: " + p.toString());
        }
    }//GEN-LAST:event_btnComisariosMostrarActionPerformed

    private void btnEliminarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAreaActionPerformed
        
        Area areaEliminar = (Area)cbxAreasEliminar.getSelectedItem();
        String mensajeEliminar = EventoController.eliminarArea(areaEliminar);
        if (mensajeEliminar == null || !mensajeEliminar.isBlank()) {
            JOptionPane.showMessageDialog(null, "Se eliminó con éxito" + areaEliminar.getNombre());
            return;
        }
        JOptionPane.showMessageDialog(null, mensajeEliminar);
    }//GEN-LAST:event_btnEliminarAreaActionPerformed

    private void txtJefeIndividualComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJefeIndividualComplejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJefeIndividualComplejoActionPerformed

    private void btnCrearComplejo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearComplejo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearComplejo1ActionPerformed

    private void btnAreasComplejo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreasComplejo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAreasComplejo1ActionPerformed

    private void btnEliminarComplejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComplejoActionPerformed
        if (cbxSelecComplejoEliminar.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(
                null,
                "Debes seleccionar al menos un comisario",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        Complejo cop = (Complejo)cbxSelecComplejoEliminar.getSelectedItem();
        
        EventoController.eliminarComplejo(cop);
        
        
        List<Complejo> cm = EventoController.getComplejos().getItems();
        cbxSelecComplejoEliminar.removeAll();
        for (Complejo c : cm){
            cbxSelecComplejoEliminar.addItem(c);
        }
        List<Area> tempArea = EventoController.getAreas().getItems();
        
        cbxSelecAreasComplejo.removeAllItems();
        
        for (Area ar : tempArea) {
            cbxSelecAreasComplejo.addItem(ar);
        }
        
        
    }//GEN-LAST:event_btnEliminarComplejoActionPerformed

    private void txtNombreAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAreaActionPerformed
    
    
    
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Olimpiada().setVisible(true));
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddComisario;
    private javax.swing.JButton btnAddEventoComplejo;
    private javax.swing.JButton btnAddSede;
    private javax.swing.JButton btnAreasComplejo;
    private javax.swing.JButton btnAreasComplejo1;
    private javax.swing.JButton btnComisariosMostrar;
    private javax.swing.JButton btnCrearArea;
    private javax.swing.JButton btnCrearComisario;
    private javax.swing.JButton btnCrearComplejo;
    private javax.swing.JButton btnCrearComplejo1;
    private javax.swing.JButton btnCrearEvento;
    private javax.swing.JButton btnCrearSede;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarArea;
    private javax.swing.JButton btnEliminarComplejo;
    private com.toedter.calendar.JCalendar caFinalEvento;
    private com.toedter.calendar.JCalendar caInicioEvento;
    private javax.swing.JComboBox<com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.Area> cbxAreasEliminar;
    private javax.swing.JComboBox<com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.Comisario> cbxComisarios;
    private javax.swing.JComboBox<com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.Comisario> cbxComisariosMostrar;
    private javax.swing.JComboBox<com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.Comisario> cbxEventoComsiarios;
    private javax.swing.JComboBox<com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.Complejo> cbxListComplejosSede;
    private javax.swing.JComboBox<com.mycompany.practicas.Semana4.Olimpiada.core.domain.enums.ComisarioRol> cbxRolComisario;
    private javax.swing.JComboBox<com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.Area> cbxSelecAreasComplejo;
    private javax.swing.JComboBox<com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.Area> cbxSelecAreasComplejo1;
    private javax.swing.JComboBox<com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.Complejo> cbxSelecComplejoEliminar;
    private javax.swing.JComboBox<com.mycompany.practicas.Semana4.Olimpiada.core.domain.models.Evento> cbxSelecEventosComplejo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label3;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label35;
    private java.awt.Label label36;
    private java.awt.Label label37;
    private java.awt.Label label38;
    private java.awt.Label label39;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label lblParticipacionesComisario;
    private java.awt.List lstAreasLista;
    private java.awt.List lstComisariosParticipaciones;
    private java.awt.List lstComisariosSeleccionados;
    private java.awt.List lstComplejosCreados;
    private java.awt.List lstComplejosSede;
    private java.awt.List lstSedesCreadas;
    private java.awt.List lstSelecEventosComplejo;
    private java.awt.List lstSelectAreasComplejo;
    private javax.swing.JTextField txtApellidoComisario;
    private javax.swing.JTextField txtDescripcionArea;
    private javax.swing.JTextField txtEventoTitle;
    private javax.swing.JTextField txtJefeIndividualComplejo;
    private javax.swing.JTextField txtLocalizacionArea;
    private javax.swing.JTextField txtLocalizacionComplejo;
    private javax.swing.JTextField txtNombreArea;
    private javax.swing.JTextField txtNombreComisario;
    private javax.swing.JTextField txtNombreComplejo;
    private javax.swing.JTextField txtNombreSede;
    private javax.swing.JTextField txtNumParticipantes;
    private javax.swing.JTextField txtPresupuestoSede;
    // End of variables declaration//GEN-END:variables
}


